---
spring:
  application:
    name: rps
  data:
    mongodb:
      uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${spring.application.name}"
  output:
    ansi:
      enabled: ALWAYS
  session:
    store-type: mongodb
